# -*- coding: utf-8 -*-
"""final project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oc8m9CIZBkd21SDE1kY_-IXfvVx5UeTz
"""

# Complete ML workflow for Cars dataset in one cell

# Step 1: Import libraries
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from google.colab import files

# Step 2: Upload CSV file
uploaded = files.upload()  # choose your Kaggle cars CSV
filename = list(uploaded.keys())[0]

# Step 3: Load dataset
df = pd.read_csv(filename)
print("Columns in dataset:", df.columns.tolist())
print("Dataset shape:", df.shape)

# Step 4: Define features and target
# Assuming the last column is the target
target_column = df.columns[-1]
X = df.drop(target_column, axis=1)
y = df[target_column]

# Step 5: Encode categorical features
categorical_cols = X.select_dtypes(include=['object']).columns
X = pd.get_dummies(X, columns=categorical_cols)

# Step 6: Scale numeric features
numeric_cols = X.select_dtypes(include=['int64', 'float64']).columns
scaler = StandardScaler()
X[numeric_cols] = scaler.fit_transform(X[numeric_cols])

# Step 7: Encode target
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Step 8: Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42
)

# Step 9: Train Random Forest Classifier
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Step 10: Predict and evaluate
y_pred = model.predict(X_test)
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le.classes_))